thresholds_2i = {
    1:
        {
            ('Tyres', 'FishSeed'): (27, 6),
            ('Fogging', 'irs'): (7, 133),
            ('Awareness', 'FishSeed'): (10, 6),
            ('Awareness', 'Tyres'): (36, 29),
            ('Fogging', 'Tyres'): (7, 29),
            ('Awareness', 'Larviciding'): (36, 14),
            ('Fogging', 'FishSeed'): (7, 5),
            ('Awareness', 'irs'): (36, 120),
            ('Dewatering', 'FishSeed'): (14, 6),
            ('irs', 'FishSeed'): (120, 6),
            ('Larviciding', 'Fogging'): (18, 7),
            ('Awareness', 'Fogging'): (11, 7),
            ('irs', 'Dewatering'): (112, 10),
            ('irs', 'Tyres'): (120, 68),
            ('Larviciding', 'FishSeed'): (11, 5)
    },
    2: {
            ('Fogging', 'irs'): (3, 4),
            ('Awareness', 'FishSeed'): (14, 2),
            ('irs', 'Ovi_Trap'): (4, 7),
            ('Awareness', 'Fogging'): (13, 3),
            ('Ovi_Trap', 'FishSeed'): (3, 2),
            ('Awareness', 'irs'): (13, 8),
            ('irs', 'FishSeed'): (5, 2),
            ('Fogging', 'Ovi_Trap'): (3, 3),
            ('Awareness', 'Ovi_Trap'): (41, 7),
            ('Awareness', 'Dewatering'): (13, 17)
    },
    3: {
            ('Fogging', 'irs'): (16, 171),
            ('Larviciding', 'Tyres'): (70, 42),
            ('Awareness', 'Tyres'): (44, 38),
            ('Awareness', 'Larviciding'): (48, 37),
            ('Awareness', 'irs'): (51, 37),
            ('Larviciding', 'irs'): (72, 171),
            ('Larviciding', 'Fogging'): (72, 19),
            ('Awareness', 'Fogging'): (48, 16),
            ('irs', 'Tyres'): (171, 26),
            ('Fogging', 'Tyres'): (19, 34)
    },
    4: {
            ('Tyres', 'FishSeed'): (21, 2),
            ('Fogging', 'irs'): (78, 110),
            ('Larviciding', 'Tyres'): (141, 28),
            ('Dewatering', 'Tyres'): (1, 19),
            ('Awareness', 'Tyres'): (5, 1),
            ('irs', 'Ovi_Trap'): (20, 1),
            ('irs', 'FishSeed'): (96, 5),
            ('Fogging', 'Tyres'): (12, 18),
            ('Awareness', 'Fogging'): (8, 29),
            ('Fogging', 'FishSeed'): (12, 2),
            ('Fogging', 'Dewatering'): (3, 1),
            ('Awareness', 'irs'): (18, 112),
            ('Dewatering', 'FishSeed'): (20, 2),
            ('Larviciding', 'irs'): (118, 116),
            ('Larviciding', 'Fogging'): (45, 24),
            ('Fogging', 'Ovi_Trap'): (2, 1),
            ('Awareness', 'Ovi_Trap'): (77, 1),
            ('irs', 'Dewatering'): (41, 1),
            ('irs', 'Tyres'): (21, 1),
            ('Awareness', 'Dewatering'): (76, 1),
            ('Larviciding', 'FishSeed'): (141, 2)
        },
    5: {
            ('Tyres', 'FishSeed'): (3, 1),
            ('Fogging', 'irs'): (6, 27),
            ('Awareness', 'FishSeed'): (11, 1),
            ('Awareness', 'Tyres'): (17, 3),
            ('Fogging', 'Tyres'): (6, 1),
            ('Awareness', 'Larviciding'): (35, 20),
            ('Larviciding', 'Tyres'): (12, 5),
            ('Fogging', 'Dewatering'): (6, 9),
            ('Awareness', 'irs'): (39, 27),
            ('Dewatering', 'FishSeed'): (8, 1),
            ('irs', 'FishSeed'): (37, 1),
            ('irs', 'Dewatering'): (37, 8),
            ('Fogging', 'FishSeed'): (6, 1),
            ('Larviciding', 'Dewatering'): (17, 9),
            ('irs', 'Tyres'): (27, 1),
            ('Awareness', 'Dewatering'): (9, 1),
            ('Larviciding', 'FishSeed'): (12, 1)
    },
    6: {
            ('Tyres', 'FishSeed'): (33, 13),
            ('Fogging', 'irs'): (7, 116),
            ('Awareness', 'FishSeed'): (90, 28),
            ('Dewatering', 'Tyres'): (19, 42),
            ('Larviciding', 'FishSeed'): (39, 13),
            ('Awareness', 'Larviciding'): (95, 39),
            ('Fogging', 'Ovi_Trap'): (6, 1),
            ('Larviciding', 'Tyres'): (39, 37),
            ('Awareness', 'irs'): (102, 322),
            ('Dewatering', 'FishSeed'): (18, 28),
            ('Larviciding', 'irs'): (40, 116),
            ('Larviciding', 'Fogging'): (40, 32),
            ('Awareness', 'Fogging'): (74, 29),
            ('irs', 'Dewatering'): (322, 55),
            ('Larviciding', 'Dewatering'): (25, 47),
            ('irs', 'Tyres'): (12, 1),
            ('Fogging', 'Dewatering'): (32, 19)
    },
    7: {
            ('Fogging', 'irs'): (1, 79),
            ('Larviciding', 'Tyres'): (29, 19),
            ('Awareness', 'Tyres'): (40, 17),
            ('Awareness', 'Larviciding'): (31, 27),
            ('Fogging', 'FishSeed'): (8, 9),
            ('Fogging', 'Dewatering'): (9, 34),
            ('Awareness', 'irs'): (171, 75),
            ('Larviciding', 'irs'): (60, 101),
            ('Larviciding', 'Fogging'): (39, 2),
            ('Awareness', 'Fogging'): (171, 9),
            ('irs', 'Dewatering'): (72, 35),
            ('Larviciding', 'Dewatering'): (1, 35),
            ('Dewatering', 'Tyres'): (35, 17),
            ('Awareness', 'Dewatering'): (33, 35),
            ('Fogging', 'Tyres'): (9, 14)
    },
    8: {},
    9: {
            ('Tyres', 'FishSeed'): (5, 2),
            ('Awareness', 'Larviciding'): (24, 9),
            ('Fogging', 'Ovi_Trap'): (5, 1),
            ('Fogging', 'Dewatering'): (17, 4),
            ('Fogging', 'irs'): (43, 9),
            ('Larviciding', 'irs'): (22, 20),
            ('Larviciding', 'Fogging'): (22, 42),
            ('Awareness', 'Fogging'): (24, 23),
            ('irs', 'Dewatering'): (9, 1),
            ('Awareness', 'Dewatering'): (24, 4)
    },
    10: {
            ('Tyres', 'FishSeed'): (17, 4),
            ('irs', 'Tyres'): (18, 17),
            ('Fogging', 'FishSeed'): (8, 4),
            ('Larviciding', 'FishSeed'): (25, 4),
            ('irs', 'FishSeed'): (18, 4),
            ('Fogging', 'irs'): (45, 17),
            ('Larviciding', 'irs'): (29, 23),
            ('Larviciding', 'Fogging'): (31, 9),
            ('Ovi_Trap', 'Tyres'): (5, 1),
            ('irs', 'Dewatering'): (18, 25),
            ('Larviciding', 'Dewatering'): (7, 28),
            ('Fogging', 'Dewatering'): (13, 38),
            ('Fogging', 'Tyres'): (12, 14)
    },
    11: {
            ('Tyres', 'FishSeed'): (20, 2),
            ('irs', 'Tyres'): (31, 16),
            ('Awareness', 'FishSeed'): (10, 2),
            ('Awareness', 'Tyres'): (19, 18),
            ('irs', 'Ovi_Trap'): (23, 1),
            ('irs', 'FishSeed'): (31, 2),
            ('Fogging', 'Tyres'): (3, 21),
            ('Awareness', 'Larviciding'): (18, 74),
            ('Larviciding', 'Tyres'): (66, 31),
            ('Fogging', 'Dewatering'): (3, 17),
            ('Fogging', 'irs'): (3, 31),
            ('Dewatering', 'FishSeed'): (18, 2),
            ('Larviciding', 'irs'): (67, 31),
            ('Larviciding', 'Fogging'): (21, 3),
            ('Awareness', 'Fogging'): (14, 3),
            ('irs', 'Dewatering'): (31, 18),
            ('Fogging', 'FishSeed'): (2, 2),
            ('Larviciding', 'Dewatering'): (74, 18),
            ('Dewatering', 'Tyres'): (17, 20),
            ('Awareness', 'Dewatering'): (16, 18),
            ('Larviciding', 'FishSeed'): (22, 2)
    },
    12: {
            ('Larviciding', 'FishSeed'): (5, 1)
    },
    13: {
            ('Tyres', 'FishSeed'): (41, 2),
            ('irs', 'Ovi_Trap'): (24, 3),
            ('Fogging', 'irs'): (52, 9),
            ('Awareness', 'Ovi_Trap'): (15, 5),
            ('Dewatering', 'Tyres'): (16, 42),
            ('Awareness', 'FishSeed'): (15, 2),
            ('Fogging', 'Tyres'): (64, 36),
            ('irs', 'FishSeed'): (9, 2),
            ('Larviciding', 'Fogging'): (23, 52),
            ('Awareness', 'Fogging'): (25, 52),
            ('Fogging', 'Dewatering'): (54, 16),
            ('Ovi_Trap', 'FishSeed'): (4, 2),
            ('Ovi_Trap', 'Tyres'): (5, 33),
            ('Larviciding', 'Tyres'): (32, 39),
            ('Awareness', 'irs'): (59, 24),
            ('Larviciding', 'irs'): (29, 24),
            ('Larviciding', 'Ovi_Trap'): (30, 6),
            ('Fogging', 'Ovi_Trap'): (51, 3),
            ('Dewatering', 'FishSeed'): (16, 2),
            ('Ovi_Trap', 'Dewatering'): (6, 11),
            ('Larviciding', 'FishSeed'): (31, 1),
            ('Fogging', 'FishSeed'): (48, 2),
            ('Awareness', 'Tyres'): (16, 41),
            ('irs', 'Dewatering'): (24, 25),
            ('Larviciding', 'Dewatering'): (36, 25)
    },
    14: {
            ('irs', 'Tyres'): (168, 37),
            ('Larviciding', 'Tyres'): (72, 37),
            ('Ovi_Trap', 'Tyres'): (6, 37),
            ('Fogging', 'Dewatering'): (2, 1),
            ('Fogging', 'irs'): (69, 25),
            ('Dewatering', 'FishSeed'): (49, 3),
            ('Larviciding', 'irs'): (69, 42),
            ('Larviciding', 'Fogging'): (35, 69),
            ('irs', 'Dewatering'): (33, 1),
            ('Larviciding', 'Dewatering'): (69, 59),
            ('Dewatering', 'Tyres'): (1, 31),
            ('Awareness', 'Dewatering'): (4, 1)
    },
    15: {
            ('Tyres', 'FishSeed'): (52, 1),
            ('Fogging', 'irs'): (42, 76),
            ('Larviciding', 'Tyres'): (60, 52),
            ('Dewatering', 'Tyres'): (86, 50),
            ('Awareness', 'Tyres'): (30, 49),
            ('Awareness', 'Larviciding'): (42, 61),
            ('Fogging', 'Dewatering'): (7, 86),
            ('Awareness', 'irs'): (30, 76),
            ('Dewatering', 'FishSeed'): (15, 4),
            ('Larviciding', 'irs'): (66, 104),
            ('Larviciding', 'Fogging'): (61, 37),
            ('Awareness', 'Fogging'): (882, 7),
            ('irs', 'Dewatering'): (76, 86),
            ('Larviciding', 'Dewatering'): (60, 86),
            ('irs', 'Tyres'): (149, 52),
            ('Awareness', 'Dewatering'): (30, 86),
            ('Fogging', 'Tyres'): (47, 52)
    },
    16: {
            ('Tyres', 'FishSeed'): (9, 3),
            ('irs', 'Tyres'): (15, 10),
            ('Awareness', 'FishSeed'): (6, 3),
            ('Awareness', 'Tyres'): (7, 9),
            ('Awareness', 'Larviciding'): (6, 2),
            ('Larviciding', 'Tyres'): (1, 8),
            ('Fogging', 'Dewatering'): (3, 1),
            ('Awareness', 'irs'): (9, 4),
            ('irs', 'FishSeed'): (11, 3),
            ('Awareness', 'Fogging'): (4, 3),
            ('irs', 'Dewatering'): (11, 2),
            ('Dewatering', 'Tyres'): (3, 10),
            ('Awareness', 'Dewatering'): (6, 1),
            ('Fogging', 'Tyres'): (3, 10)
    },
    17: {
            ('Larviciding', 'Fogging'): (2, 2),
            ('Awareness', 'Tyres'): (4, 2)
    },
    18: {
            ('Awareness', 'irs'): (111, 89),
            ('Fogging', 'irs'): (96, 89),
            ('Fogging', 'Tyres'): (16, 12),
            ('Awareness', 'Tyres'): (5, 12),
            ('Awareness', 'Fogging'): (5, 16)
    },
    19: {
            ('irs', 'Ovi_Trap'): (2, 3),
            ('Fogging', 'irs'): (3, 2),
            ('Awareness', 'Ovi_Trap'): (12, 3),
            ('Awareness', 'FishSeed'): (17, 1),
            ('Larviciding', 'FishSeed'): (35, 1),
            ('Awareness', 'Larviciding'): (173, 28),
            ('irs', 'Tyres'): (66, 7),
            ('irs', 'FishSeed'): (2, 1),
            ('Larviciding', 'Fogging'): (47, 3),
            ('Awareness', 'Fogging'): (173, 3),
            ('Fogging', 'Dewatering'): (6, 5),
            ('Ovi_Trap', 'FishSeed'): (3, 1),
            ('Awareness', 'irs'): (5, 2),
            ('Larviciding', 'irs'): (18, 66),
            ('Larviciding', 'Ovi_Trap'): (62, 3),
            ('Fogging', 'Ovi_Trap'): (6, 3),
            ('Dewatering', 'FishSeed'): (5, 1),
            ('Ovi_Trap', 'Dewatering'): (3, 6),
            ('Fogging', 'FishSeed'): (3, 1),
            ('irs', 'Dewatering'): (69, 5),
            ('Larviciding', 'Dewatering'): (55, 5),
            ('Awareness', 'Dewatering'): (173, 5)
    },
}


thresholds_1i = {
        'Tyres': 262,
        'FishSeed': 45,
        'Larviciding': 588,
        'irs': 886,
        'Awareness': 338,
        'Dewatering': 0,
        'Ovi_Trap': 8,
        'Fogging': 36
}